app/Http/routes.php
<?php

Route::get('/', function(){
    return redirect('/patient');
});

Route::get('/landing', 'Doctor\PagesController@landing');
Route::post('/kimonofeeds', 'KimonoFeedsController@index');
Route::get('/kimonofeedsGet', 'KimonoFeedsController@get');
Route::get('/phpinfo', function(){
    phpinfo();
});

// Authentication Routes
Route::get('verify/{code}', ['as' => 'verify_user', 'uses' => 'UsersController@verify']);
Route::post('mail', ['as' => 'send_mail' , 'uses' => 'MailController@send_mail']);
Route::post('refer', ['as' => 'refer.send' , 'uses' => 'MailController@sendReferral']);

/**
 * Handle Queues
 */
Route::post('queue/receive', 'QueuesController@receive');


Route::get('forgot-password', [
    'as' => 'password.forgot',
    'uses' => 'Auth\PasswordController@getEmail'
]);

Route::get('patient/forgot-password', [
    'as' => 'patient.password.forgot',
    'uses' => 'Auth\PasswordController@getEmailPatient'
]);

Route::post('forgot-password', [
    'as' => 'password.forgot',
    'uses' => 'Auth\PasswordController@postEmail'
]);

Route::get('password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'Auth\PasswordController@getReset'
]);

Route::post('password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'Auth\PasswordController@postReset'
]);

Route::get('resend-verification', [
    'as' => 'resend-verify.create',
    'uses' => 'Auth\AuthController@getResend'
]);

Route::post('resend-verification', [
    'as' => 'resend-verify.execute',
    'uses' => 'Auth\AuthController@postResend'
]);

Route::get('doctor-premium-callback','ServiceController@doctorPaymentCallback');
Route::get('hospital-premium-callback','ServiceController@hospitalPaymentCallback');
Route::get('payment-callback','ServiceController@paymentCallback');

require_once(app_path().'/Routes/patient.php');
require_once(app_path().'/Routes/doctor.php');
require_once(app_path().'/Routes/admin.php');

app/Models/Hospital.php
<?php namespace MEDoctors\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

use Nicolaslopezj\Searchable\SearchableTrait;
use MEDoctors\Models\HospitalClaim;
use Illuminate\Support\Facades\Auth;

class Hospital extends Model {

    use SearchableTrait;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'slug' , 'description' , 'website' , 'verified'];

    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        'columns' => [
            'name' => 10,
        ]
    ];

    /**
     * Get the location of the hospital.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function location()
    {
        return $this->morphOne('MEDoctors\Models\Location', 'locationable');
    }

    /**
     * a hospital has many views.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function views()
    {
        return $this->morphMany('MEDoctors\Models\View' , 'viewable');
    }

    /**
     * a hospital has many views.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function doctors()
    {
        return $this->belongsToMany('MEDoctors\Models\User' , 'hospital_doctors');
    }

    /**
     * Gets the avatar for the hospital
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailAttribute()
    {
        $thumb = $this->avatar()->first();

        return $thumb ? 'public/'.$thumb->url : asset('images/placeholders/hospital.png');
    }

    /**
     * Gets the primary phone number for the hospital
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getPhoneNumberAttribute()
    {
        $phone_numbers = $this->contacts()->get();
        return count($phone_numbers)>0 ? $phone_numbers[0]->number : 'N/A';
    }

    /**
     * Gets the primary phone number for the hospital
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getClaimedByCurrentUserAttribute()
    {
        $hospital = $this;
        $user = Auth::user();

        if($user){

            $claimed= HospitalClaim::where('hospital_id',$hospital->id)
                ->where('user_id',$user->id)
                ->where('verified',0)
                ->first();

            if($claimed)
                return true;
        }

        return false;
    }

    /**
     * Gets the primary phone number for the hospital
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getOwnedByCurrentUserAttribute()
    {
        $hospital = $this;
        $user = Auth::user();

        if($user){

            $claimed= HospitalClaim::where('hospital_id',$hospital->id)
                ->where('user_id',$user->id)
                ->where('verified',1)
                ->first();

            if($claimed)
                return true;
        }

        return false;
    }

    /**
     * Check if user is premium.
     *
     * @return int
     */
    public function getCurrentServiceAttribute()
    {
        $service = $this->services()->where('expires_on', '>' , date("Y-m-d H:i:s"))->first();

        return $service ? $service : false;
    }

    /**
     * Gets the primary phone number for the hospital
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getOwnedBySomeoneAttribute()
    {
        $hospital = $this;
        $user = Auth::user();

        if($user){

            $claimed= HospitalClaim::where('hospital_id',$hospital->id)
                ->where('verified',1)
                ->pluck('user_id');

            if($claimed)
                return true;
        }

        return false;
    }


    /**
     * Gets the City and Country of the hospital
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getBasicLocationAttribute()
    {
        $location = $this->location;

        if ( ! $location or ! $location->city or ! $location->country)
        {
            return 'N/A';
        }

        return $location->city . ', '. $location->country;
    }

    /**
     * a hospital has an avatar.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function avatar()
    {
        return $this->morphOne('MEDoctors\Models\Upload', 'uploadable');
    }

    /**
     * A hospital user has many schedules.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function schedules()
    {
        return $this->hasMany('MEDoctors\Models\HospitalSchedule');
    }

    /**
     * A hospital has therapies.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */

    public function therapies()
    {
        return $this->belongsToMany('MEDoctors\Models\Therapy', 'hospital_therapies');
    }

    /**
     * A hospital has facilities.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */

    public function facilities()
    {
        return $this->belongsToMany('MEDoctors\Models\HospitalFacility', 'hospital_facility_users');
    }

    /**
     * a hospital has many views.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function claims()
    {
        return $this->belongsToMany('MEDoctors\Models\HospitalClaim');
    }

    /**
     * A hospital can have multiple phone numbers.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function contacts()
    {
        return $this->morphMany('MEDoctors\Models\PhoneNumber', 'phoneable');
    }


    /**
     * a user can be a KOL.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function services()
    {
        return $this->hasOne('MEDoctors\Models\ServiceHospitalUser','hospital_id');
    }

    /**
     * Combine the location attributes and return the whole address.
     *
     * @return string
     */
    public function getAddressAttribute()
    {
        $location = $this->location;
        $location = $location->street_number . ' '
                    . $location->street_route . ' '
                    . $location->state . ', '
                    . $location->city . ', '
                    . $location->country;

        return trim($location);
    }

    /**
     * Combine the location attributes and return the whole address.
     *
     * @return string
     */
    public function getDetails($request)
    {
        $data = [];
        foreach($request as $index=>$item){
            if($item['name']!=""){
                $data[$index] =  new static([
                    'name' => $item['name'],
                    'slug' => Str::slug($item['name']),
                    'verified' => 0
                ]);
            }
        }

        return $data;
    }

    /**
     * Combine the location attributes and return the whole address.
     *
     * @return Array
     */
    public function generateSchedule($user_id , $request)
    {
        foreach($request as $index=>$day){
            $data[$index] = [
                'user_id' => $user_id,
                'day'         => $day['day']
            ];
        }

        return $data;
    }

    /**
     * Generate Contact Proper format for create.
     *
     * @return Array
     */
    public function generateContactCreateData($contacts)
    {
        $data = null;
        if(count($contacts)>0){
            foreach($contacts as $index=>$contact){
                $data[$index] = [
                    'number' => $contact,
                    'type'   => $index<1 ? 'Primary' : 'Secondary'
                ];
            }
        }
        return $data;
    }

    /**
     * Generate Contact Proper format for create.
     *
     * @return Array
     */
    public function generateFacilitiesCreateData($facilities)
    {
        $data = null;
        if(count($facilities)>0){
            foreach($facilities as $index=>$facility){
                $data[$index] = [
                    'hospital_facility_id' => $facility,
                ];
            }
        }

        return $data;
    }

    /**
     * Generate Contact Proper format for create.
     *
     * @return Array
     */
    public function generateTherapiesCreateData($therapies)
    {
        $data = null;
        if(count($therapies)>0){
            foreach($therapies as $index=>$therapy){
                $data[$index] = [
                    'therapy_id' => $therapy,
                ];
            }
        }

        return $data;
    }

    /**
     * Check if user is premium.
     *
     * @return int
     */
    public function getIsPremiumAttribute()
    {
        if ($this->services()->where('active',1)->count())
            $flag = 1;
        elseif ($this->services()->where('active',0)->count())
            $flag = 2;
        else
            $flag = 0;

        return $flag;
    }

    /**
     * Check if user is premium.
     *
     * @return int
     */
    public function getPremiumAttribute()
    {
        if(isset($this->active))
            if($this->active)
                return true;

        return false;
    }
}

app/Models/Profile.php
<?php namespace MEDoctors\Models;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model {

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id' , 'avatar_id' , 'bio'];
        
    /**
     * Gets the avatar for the profile.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphOne
     */
    public function avatar()
    {
        return $this->morphOne('MEDoctors\Models\Upload', 'uploadable');
    }

    public function createInstance($request){
        return new static([
            'bio' => $request['bio']
        ]);
    }

}

resources/views/doctor/pages/hospitals/profile/about.blade.php
<div class="fields padding-b-7 clearfix">
<h1 class="t-yellow margin-t-20 margin-b-4 clearfix pull-left width-full">About</h1>
    <div class="col-md-12 padding-l-0">
        <span>
            {!! trim($hospital->description) == '' ? 'No description' : $hospital->description !!}
        </span><br>
    </div>
</div>

resources/views/doctor/pages/hospitals/profile/doctors.blade.php
@if($hospital->doctors)
    @if(count($hospital->doctors))
    <div class="fields padding-b-7 clearfix">
    <h1 class="t-yellow margin-t-20 margin-b-7 clearfix pull-left width-full">Doctors</h1>
        <div class="col-md-12 padding-l-0">
            @foreach($hospital->doctors as $doctor)
                <div class="col-md-3">
                    <a href="{{ route('doctor.profile',$doctor->username) }}">
                        <div class="row">
                            <div class="col-md-4 no-padding margin-b-10">
                                <img src="{{ asset($doctor->avatar) }}" width="100%">
                            </div>
                            <div class="col-md-8 padding-r-0">
                                <h4 class="margin-t-4">{{ $doctor->fullName }}</h4>
                            </div>
                        </div>
                    </a>
                </div>
            @endforeach
        </div>
    </div>
    @endif
@endif

resources/views/doctor/pages/hospitals/profile/facilities.blade.php
<div class="padding-b-7 clearfix">
@if(count($hospital->facilities)>0)
    <h1 class="t-yellow margin-t-20 margin-b-7 clearfix pull-left width-full">Facility Keys</h1>
    <div class="col-md-12 padding-l-0 facilities">
        @foreach($hospital->facilities as $facility)
            <span class="facility-icon {{ $facility->slug }}"></span> {{ $facility->name }}
        @endforeach
    </div>
@endif
</div>

resources/views/doctor/pages/hospitals/profile/location.blade.php
<div class="fields padding-b-7 clearfix">
<h1 class="t-yellow margin-t-20 margin-b-4 clearfix pull-left width-full">Location</h1>
    <div class="col-md-4 padding-l-0 line-height-22">
        <span>{!! '<b>'. $hospital->name . '</b><br>'  !!}</span>
        <span><b>
            {{ $hospital->basicLocation }}
        </b><br></span>
        <span>
            {!! $hospital->location ? $hospital->location->name : ''  !!}
        <br></span>
    </div>

    <div class="col-md-8 no-padding">
        <div class="map" style="height: 300px">
        </div>
    </div>
</div>

resources/views/doctor/pages/hospitals/profile/main.blade.php
<div class="hs_single_profile_detail padding-b-20 clearfix">
    <div class="row">
        <div class="col-md-4 col-sm-4 padding-b-0">
            @if($hospital->isPremium == 1)
                <span class="featured-ribbon yellow doctor"></span>
            @endif
            <img src="{{ asset($hospital->thumbnail) }}" alt="{{ $hospital->name }}" width="100%"/>
        </div>
        <div class="col-md-8 col-sm-8 ">
            <div class="col-lg-12 col-md-12 col-sm-12 margin-tb-0margin-tb-0 padding-tb-0">
                <div class="row">
                    <h3 class="margin-t-7 margin-tb-0 text-uppercase">{{ $hospital->name }}</h3>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 margin-tb-0 padding-tb-0">
                <div class="row">
                  <h4 class="margin-tb-10">
                  </h4>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 margin-tb-0 padding-tb-0">
                    <div class="row line-height-22">
                        <span class="small-icon yellow cursor"></span> {!! $hospital->website ? '<a target="_blank" href=http://'.$hospital->website.'>'.$hospital->website . '</a>' : 'No website' !!} <br>
                        <span class="small-icon yellow phone"></span> {{ $hospital->phoneNumber }} <br>
                        <table>
                            <tr>
                                <td class="pull-left"><span class="small-icon yellow location"></span></td>
                                <td> {{ preg_replace( "/\r|\n/", "", $hospital->location ? $hospital->location->name : 'Not available' ) }}</td>
                            </tr>
                        </table>
                        @if(Session::has('message'))
                            <div class="alert alert-success margin-t-10 ">{!!  Session::get('message') !!}</div>
                        @elseif($hospital->ownedByCurrentUser)

                            <a href="{{ route('doctor.hospitals.edit', $hospital->slug) }}">
                                <button class="button t-light-gray">[ <i class="fa fa-edit"></i> EDIT ]</button>
                            </a>

                            @if($hospital->currentService)
                                <span class="t-pink">( Premium service expires on : {{ $hospital->currentService->expires_on->format('m-d-Y') }} )</span>
                            @endif

                            @if(!$hospital->isPremium && $authUser->id==1)
                                <a href="#" data-target="#premium" data-toggle="modal" class="button">
                                    <button class="button t-light-gray">[ <i class="fa fa-star-o"></i> UPGRADE ACCOUNT ]</button>
                                </a>
                            @endif
                        @elseif(!$hospital->ClaimedByCurrentUser)
                            <a class="margin-t-20 padding-l-5" href="#" data-toggle="modal" data-target="#claim">
                                <i class="fa fa-check-circle-o"></i> Claim this hospital
                            </a>
                        @else
                             @if(isset($claim))
                                <a href="#" class="margin-t-10 alert alert-success">Your claim request has been sent successfully. If approved, a final verification email will be sent to {{ $claim }}</a>
                            @endif
                        @endif
                    </div>
                </div>
            </div>
            </div>
    </div>
</div>

resources/views/doctor/pages/hospitals/profile/specialties.blade.php
<div class="hs_single_profile_detail padding-b-10 clearfix">
    <h1 class="t-yellow margin-t-7 margin-b-4">Specialties</h1>
    @if($hospital->therapies && count($hospital->therapies) > 0)
        @foreach($hospital->therapies as $index=>$specialty)
          {{ $specialty->name }}{{  ($index+1) < count($hospital->therapies) ? ', ' : '' }}
        @endforeach
    @else
        Not set.
    @endif
</div>